### ISSUE TITLE
Generate a 404 Page

### ISSUE THREAD

**Issue by AndrewKahr** [Simply-Static/simply-static#100]
Is there a way to generate a 404 page with simply static?

**Comment by derekperkins** [comment]
In the short term, if you add `/404.php` to urls to crawl, it will generate `404.html`, which is used by at least Cloudflare Pages

**Comment by crstauf** [comment]
I added `/404.php` to the list of URLs to include, but no `404.html` was created.

**Comment by crstauf** [comment]
It seems the plugin discards any pages that throw `404`, which makes sense.

**Comment by chrisdavidmiles** [comment]
I was able to work around it by adding /404.html to the additional urls setting, and then adding this to my functions.php to make sure it returned a 200 status if the page url is 404.html. That way I can use my theme's 404 page but the page doesn't get skipped. I know it's a kind of ugly workaround but that's how I'm making it work.

```
add_filter( 'status_header', 'simply_static_404_workaround', 10, 2 );

function simply_static_404_workaround( $status_header, $header ) {

    // if the url is /404.html
    if ($_SERVER['REQUEST_URI'] == '/404.html'){

        // and if that page throws a 404, actually use 200 status.
        if ( (int) $header == 404 )
            return status_header( 200 );
    }

    // otherwise, return unchanged header
    return $status_header;

}
```

**Comment by crstauf** [comment]
Thanks, @chrisdavidmiles, better than my current workaround.
