### ISSUE TITLE
FusionBuilder - Extracting images (src and CSS)

### ISSUE THREAD

**Issue by aravindnc** [Simply-Static/simply-static#121]
In below case only the src image seems to be downloading, causing issues in responsive views.

```<img decoding="async" width="512" height="512" title="care-image" src="/wp-content/uploads/2022/07/care-image.png" data-orig-src="/wp-content/uploads/2022/07/care-image.png" alt="" class="img-responsive wp-image-1019 lazyautosizes lazyloaded" srcset="/wp-content/uploads/2022/07/care-image-200x200.png 200w, /wp-content/uploads/2022/07/care-image-400x400.png 400w, /wp-content/uploads/2022/07/care-image.png 512w" data-srcset="/wp-content/uploads/2022/07/care-image-200x200.png 200w, /wp-content/uploads/2022/07/care-image-400x400.png 400w, /wp-content/uploads/2022/07/care-image.png 512w" data-sizes="auto" data-orig-sizes="(max-width: 1024px) 100vw, (max-width: 640px) 100vw, 400px" sizes="140px">```

Suggestion: To add an option to download all images in uploads folder, using something like **/wp-json/wp/v2/media** API.

Thanks in advance.

**Comment by patrickposner** [comment]
Copied from: https://github.com/patrickposner/simply-static/issues/120

Here you can see there is image in the inline style, which is not downloaded when i tried to use the plugin.

Any idea on how to make this work. Every other thing works perfect!

<div class="fusion-column-wrapper fusion-flex-justify-content-flex-start fusion-content-layout-column lazyloaded" style="background-position: left top; background-blend-mode: overlay; background-repeat: no-repeat; background-size: cover; background-color: rgba(0, 0, 0, 0.3); padding: 90px 0px; background-image: url(&quot;/wp-content/uploads/2020/04/sides-menu-background.jpg&quot;);" data-bg-url="/wp-content/uploads/2020/04/sides-menu-background.jpg" data-bg="/wp-content/uploads/2020/04/sides-menu-background.jpg">
<style type="text/css">@media only screen and (max-width:1024px) {.fusion-title.fusion-title-10{margin-top:0px!important; margin-right:0px!important;margin-bottom:0px!important;margin-left:0px!important;}}@media only screen and (max-width:640px) {.fusion-title.fusion-title-10{margin-top:0px!important; margin-right:0px!important;margin-bottom:0px!important; margin-left:0px!important;}}.fusion-title.fusion-title-text.fusion-title-10 a{color:#212934}.fusion-title.fusion-title-text.fusion-title-10 a:hover{color:#006439}</style>
<div class="fusion-title title fusion-title-10 fusion-sep-none fusion-title-center fusion-title-text fusion-title-size-two" style="font-size:1.2em;margin-top:0px;margin-right:0px;margin-bottom:0px;margin-left:0px;"><h2 class="title-heading-center fusion-responsive-typography-calculated" style="margin:0;font-size:1em;letter-spacing:1px;color:#ffffff;--fontSize:18;--minFontSize:1.2em;line-height:1.2;"><a href="/menu" class="awb-custom-text-color awb-custom-text-hover-color" target="_self"><span style="color: #ffffff;">SIDES</span></a></h2></div>
</div>
