### ISSUE TITLE
`Unexpected token '` with WP Migrate

### ISSUE THREAD

**Issue by Striffly** [Simply-Static/simply-static#125]
Hi

Problem
------
When I pull remote database with WP Migrate, I got the following error :

![image](https://user-images.githubusercontent.com/13284087/227195275-51e887ef-053f-46b1-9515-71a76e89412c.png)

This error occurs with `wp_simply_static_pages` table only.

Temporary workaround
------
Unselect `wp_simply_static_pages` table when pulling database

Versions
------
Wordpress : 6.1.1
PHP : 7.4
WP Migrate : 2.6.3
Simply Static : 2.2.8
Simply Static Pro : 1.2.4.5

**Comment by patrickposner** [comment]
Hey @Striffly,

thanks for bringing that up.

Sadly, that's been an issue for years, but I never found the time to fix it.
I will add it to the milestone for the next release, and we will take a look!

**Comment by pixeline** [comment]
Just want to say that I use the WP Migrate plugin and does not have that issue. It might be useful to document this issue with  a dump of that table so that the content can be inspected?

**Comment by patrickposner** [comment]
I tested that now as well without any issues.

I will close the issue for now, but if you still run into problems, feel free to post an update here, and we will reopen the issue.

Cheers,
Patrick
