### ISSUE TITLE
Generated pages missing when AIOSEO Crawl Cleanup is active

### ISSUE THREAD

**Issue by sr293** [Simply-Static/simply-static#127]
Simply Static appears to not generate all pages when the Crawl Cleanup option is enabled in All In One SEO Plugin version 4.3.3.

**Steps to reproduce:**

1. Install ALL In One SEO Plugin
2. Navigate to the Advanced tab under AIOSEO > Search Appearance
3. Toggle on the Crawl Cleanup option
4. Disable the "Static Posts Page Feed"
5. Generate the site in Simply Static under Simply Static > Generate

**Site Info:**
[site-info.txt](https://github.com/Simply-Static/simply-static/files/11102898/site-info.txt)

**Images:**
![simply-static_aioseo_1](https://user-images.githubusercontent.com/54094654/228598378-7e87045a-85d1-4225-bdff-ac1aa474fec6.png)
![simply-static_aioseo_2](https://user-images.githubusercontent.com/54094654/228598376-34e3e0c0-b569-496c-88d9-0e087f268efa.png)
![simply-static_aioseo_3](https://user-images.githubusercontent.com/54094654/228598374-19e0eb86-e731-444b-8890-36a8a25e696a.png)
![simply-static_aioseo_4](https://user-images.githubusercontent.com/54094654/228598370-c23b0e65-edc0-434b-9c76-095dc43b640c.png)

**Comment by igorbenic** [comment]
Couldn't find Static Page Feed to disable but I saw less number of pages generated when this was activated.

Provided a PR to fix it.
