### ISSUE TITLE
Version 2.2.8 did not fix the Yoast sitemap.xml issue

### ISSUE THREAD

**Issue by BenJackGill** [Simply-Static/simply-static#132]
Simply Static Version 2.2.8 change log has an update saying `improved XML Sitemap handling with Yoast SEO` which I assumed was talking about this [issue that was fixed and merged](https://github.com/Simply-Static/simply-static/issues/107).

**Quick recap of that issue**: Yoast generates a sitemap at `sitemap_index.xml` and then redirects `sitemap.xml` to `sitemap_index.xml`. Therefore when a static site was generated there was no sitemap found at `sitemap.xml` because the redirect was lost.

Was this issue fixed in version 2.2.8? Because I am using 2.2.9 and my static site still doesn't generate `sitemap.xml`. It only generates `sitemap_index.xml`. So it seems this fix did not work and the original problem still exists.

**Comment by igorbenic** [comment]
@BenJackGill when generating is done, for me, it creates both sitemap_index.xml & sitemap.xml (copies the file sitemap_index.xml and renames it).

I'll look into introducing more logging parts so we can find out why such would happen to some.

Do you automatically deploy the site somewhere? Does sitemap.xml exist in wp-content/plugins/simply-static/static-files/simply-static-{site-id}-{timestamp}?

**Comment by BenJackGill** [comment]
The site is not automatically deployed anywhere. The delivery method is "local directory".

When I check `wp-content/plugins/simply-static/static-files/simply-static-{site-id}-{timestamp}` I can see `sitemap.xml` but when I check the local output directory `sitemap.xml` is not there.

Incase it helps, here's some environment info:

- Running locally on LocalWp version 6.7.0
- PHP 8.1.9
- MySQL 8.0.16
- WordPress 6.2
- Simply Static 2.2.9
- Yoast SEO 20.4

**Comment by patrickposner** [comment]
Hey @BenJackGill,

just asking as we can't replicate the issue: are you using Yoast SEO Premium?

**Comment by BenJackGill** [comment]
I am not using Yoast SEO Premium.

I just ran a test on a brand new site, and the problem remains.

**Here are the steps for reproduction:**

1. Open LocalWP and create a new site.
2. Open WordPress admin and download Simply Static + Yoast plugins.
3. Under Simply Static > Settings > Delivery Method choose "Local Delivery"
4. Create a new "public_static" folder in `/Users/YOUR_USER/Local Sites/YOUR_SITE_NAME/app/public_static/`
5. Under Simply Static > Settings > Local Directory input the path to the "public_static" created above. For example, `/Users/YOUR_USER/Local Sites/YOUR_SITE_NAME/app/public_static/`
6. Save Changes
7. Generate the files
8. Look inside the "public_static" folder created above (`/Users/YOUR_USER/Local Sites/YOUR_SITE_NAME/app/public_static/`) and there is no `sitemap.xml` file.

**My environment:**

- MacOs Ventura 13.3
- PHP 8.1.9
- MySQL 8.0.16
- Web server Nginx
- Yoast Plugin (free version, not premium) 20.5
- Simply Static Plugin 2.2.9
- Twenty Twenty Three theme

This was on a fresh install. No other plugins or themes were added.

Also are you sure you're looking in side the "Local Directory"? Because the I can see `sitemap.xml` in the "Temporary Files Directory" but I cannot see it in the "Local Directory".

To be clear...

- I can see `sitemap.xml` here in the "Temporary Files Directory": `/Users/BenJackGill/Local Sites/test/app/public/wp-content/plugins/simply-static/static-files/`
- But I cannot see `sitemap.xml` here in the "Local Directory": `/Users/BenJackGill/Local Sites/test/app/public_static/`

Here is a screenshot of the generated static files found in "Local Directory" (`/Users/BenJackGill/Local Sites/test/app/public_static/`):

<img width="710" alt="Screenshot 2023-04-21 at 4 46 24 pm" src="https://user-images.githubusercontent.com/2043257/233606756-648fb68e-97de-4709-8d68-c6bea790027d.png">

**Anything else you need please let me know! Happy to help :)**

**Comment by patrickposner** [comment]
Hey @BenJackGill,

it's fixed now.

I was able to replicate it and modified the Yoast integration to also pick up the general sitemap.xml before triggering the local transfer task to ensure it's included in the destination directory.
