### ISSUE TITLE
Simply Static's output is illegible

### ISSUE THREAD

**Issue by senoj26** [Simply-Static/simply-static#148]
- I have a small wordpress site that I would like to export static files for to upload to Cloudflare for hosting.
- I installed the Simply Static plugin and created an export, but the plugin did not seem to find the links to my other pages (only exported index.html)

The main issue I am having is that the output of the generated index.html is unreadable:
Snippet (approx 1/4 of the total output): ``QùÇI¼•8{lï·çTRÀ„ X ÔeUík|Uç¼Ü>Éé àE”½Nb_$``

Any idea what is causing this? This is likely an issue of user error, so apologies in advance. I also know this is not a ton of information, but I am happy to provide whatever else you may need.

**Comment by sr293** [comment]
Hello @senoj26. Do you have any optimization plugins active in your WordPress install of hosting environment? You may want to try disabling all plugins except for Simply Static and reactivating them one at a time to help determine the source of the issue. Also you could use the debug feature located at the bottom of the Simply Static > Diagnostics admin page to create a log file during static generation that may provide valuable insight into the matter.
