### ISSUE TITLE
WP Emoji Script not autodetected

### ISSUE THREAD

**Issue by AndrewKahr** [Simply-Static/simply-static#151]
I'm not sure if it's my theme or elementor but something always pulls in wp-emoji, however simply static doesn't automatically detect it so I get errors on my page unless I manually add it as a URL.

The reference to it is here:

```
window._wpemojiSettings = {"baseUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/72x72\/","ext":".png","svgUrl":"https:\/\/s.w.org\/images\/core\/emoji\/14.0.0\/svg\/","svgExt":".svg","source":{"concatemoji":"https:\/\/mywebsiteurl.com\/wp-includes\/js\/wp-emoji-release.min.js?ver=6.2.2"}};
```

**Comment by patrickposner** [comment]
I'm closing that one and linking to it from the other issue.

The problem seems to be similar (parsing base64 encoded URLs to include the emoji script).
