### ISSUE TITLE
Docker - "Not a valid url"

### ISSUE THREAD

**Issue by Jakob002** [Simply-Static/simply-static#153]
### My setup:
I am currently running Simply Static from inside a dockerized wordpress instance.
The container's port mapping is 8080:80 (port 8080 from the outside world, port 80 from inside the container).
SSL is off.
My Docker installation uses a public DNS.
However my dev machine sits inside my local network.
Simply Static version is 2.3.1.
Wordpress version is 6.2.2.
Docker image is wordpress:6.2.2-apache.

### My problem:
Simply static is not working.
"Generate" page loads forever.
"Diagnostics" page indicates "Checking if WordPress can make requests to itself from 172.x.y.z - Not a valid url"

### What I suspect:
I suspect that Simply Static either uses the "wrong" host (that the public DNS cannot resolve), the "wrong" port (using 8080 when it should use 80), or the wrong protocol (https).

### What I tried:
I bashed into my container and cURLed localhost:80 and 172.x.y.z:80. Both succeeded.
I tried looking at Apache's access logs, but they didn't show any incoming requests from inside the container (other than my own cURL requests).
I also tried googling and found several posts on stackoverflow with similar problems. Unfortunately none of the answers worked for me. (However, I'm a bit sleep deprived because of the current heat wave.)

### My question/suggestion/feature request:
Could you please have a look at this? Can anybody reproduce?
Unfortunately I'm no good with PHP. Could you clarify what protocol, host and port Simply Static uses for crawling and how it determines those values?
If protocol, host or port are in fact the issue, could you perhaps make an "advanced option" to override whatever values Simply Static would normally use?

Kind regards.

**Comment by Jakob002** [comment]
Sorry, just now I found the "Debugging Mode" located under Simply Static > Diagnostics.

The logs show that Simply Static indeed uses the "correct" protocol, the "wrong" host and "wrong" port. Basically it uses whatever you have under WordPress settings > WordPress Address (URL) and Site Address (URL).

So could you please add an optional override for those values?

**Comment by patrickposner** [comment]
Hey @Jakob002,

thanks for reaching out!

That was exactly what I was going to say :-)
There are plenty of filters implemented into Simply Static to modify that.

The most common one (originally implemented to handle reverse proxy setups) is this one:

` apply_filters( 'ss_origin_url', untrailingslashit( home_url() ) )`

The origin URL is what is being fetched from the settings in WordPress and used to perform the checks in the diagnostics. It's also the main point of interaction once we start crawling.

By using that filter, you can replace that URL with the "correct" one like so:

`add_filter( 'ss_origin_url', function ( $origin_url ) {
	$my_custom_origin_url = 'https://www.example.com';
	return untrailingslashit( $my_custom_origin_url );
} );`
