### ISSUE TITLE
Still getting timed-out even after enabling WP-CRON

### ISSUE THREAD

**Issue by Wdits** [Simply-Static/simply-static#156]
So i'm trying to export a large site, running locally with the "flywheel local" app. but after many tries and even after enabling wp-cron through the wp config and all i keep getting the same "An error occurred: cURL error 28: Operation timed out after 30005 milliseconds with 0 bytes received" messages, also it seems like it manages to generate the index page, but the whole page is broken
![image](https://github.com/Simply-Static/simply-static/assets/123775432/064b3990-fcd4-4b43-af75-afd02b93b3e1)

![image](https://github.com/Simply-Static/simply-static/assets/123775432/81bf9051-6b8d-45d1-b5d8-02ce2673dff3)

checked the diagnostics page and it's all on green idk what to do, maybe it isnt compatible with divi? any help would be appreciated tyy.

**Comment by patrickposner** [comment]
Hey @Wdits,

thanks for reaching out.

Not sure if we can help here, as this is specific to your hosting setup, but it does look like WP-Cron is still not running correctly.
It might not be enough to enable it via wp-config.php if your server hasn't implemented a way to handle cron jobs.

Is this a local environment?

You may want to check our docs article about that (XAMP and MAMP don't ship with a working cron implementation out of the box): https://simplystatic.com/docs/problems-with-local-development/

Cheers,
Patrick
