### ISSUE TITLE
Possible issue with Elementor Carousel element after updating to 2.3.2

### ISSUE THREAD

**Issue by xavivalenti** [Simply-Static/simply-static#157]
Hi

After updating the simply-static to last version 2.3.2 I faced an issue when using an Elementor Carousel element.

I do not have a copy of simply static 2.3.1 to test and asure the issue. I will apreciate if I can download from somewhere to test again.

I noticed that simply static adds some quotes in data-settings for a carousel.

This is the original HTML data settings:
`data-settings='{"slides_to_show":"2","lazyload":"yes","autoplay":"no","navigation":"both","infinite":"yes","speed":500,"image_spacing_custom":{"unit":"px","size":20,"sizes":[]},"image_spacing_custom_tablet":{"unit":"px","size":"","sizes":[]},"image_spacing_custom_mobile":{"unit":"px","size":"","sizes":[]}}'`

This is the HTML data settings of the static page:

`data-settings='{"slides_to_show":"2","lazyload":"yes","autoplay":"no","navigation":"both","infinite":"yes","speed":"500","image_spacing_custom":{"unit":"px","size":"20","sizes":[]},"image_spacing_custom_tablet":{"unit":"px","size":"","sizes":[]},"image_spacing_custom_mobile":{"unit":"px","size":"","sizes":[]}}'`

You can see the numbers 500 and 20 includes quotes in the statis version but they are not present at the beginning. Removing the quotes makes the static page works properly.

Thanks in advance

**Comment by snap360-zach** [comment]
Modifying replace_urls_in_text to return a numeric value for numbers instead of making them strings seemed to work over here but need to test more.

Basically just added a check to the start of the function

public function replace_urls_in_text( $string ) {
    if ( is_numeric( $string ) ) {
        return $string + 0;
    }
.

**Comment by patrickposner** [comment]
Patched in 3.0.8 now.
