### ISSUE TITLE
 sitemap in robots.txt still pointing to development server

### ISSUE THREAD

**Issue by kevinlaw91** [Simply-Static/simply-static#159]
Added `http://project.test/robots.txt` manually, but the sitemap entry in `robots.txt` is not replaced

```Sitemap: http://project.test/sitemap.xml```

Using The SEO Framework btw, not sure if supported because `sitemap.xsl` is not parsed too.

**Comment by patrickposner** [comment]
Hey @kevinlaw91,

thanks for letting us know!

We haven't found the time to support The SEO Framework yet, but I'm happy to add that to our roadmap now.

**Comment by cotusandro** [comment]
@patrickposner, Do you have any update?

**Comment by dmeagor** [comment]
doesn't work with yoast robots.txt either.
