### ISSUE TITLE
Fatal error in class-ss-fetch-urls-task.php

### ISSUE THREAD

**Issue by jan-koch** [Simply-Static/simply-static#160]
Hey, when running an export on version 3.0.3, I get this error:

``[26-Jul-2023 15:21:20 UTC] PHP Fatal error:  Uncaught TypeError: explode(): Argument #2 ($string) must be of type string, array given in /var/www/html/wp-content/plugins/simply-static.3.0.3/src/tasks/class-ss-fetch-urls-task.php:271
Stack trace:
#0 /var/www/html/wp-content/plugins/simply-static.3.0.3/src/tasks/class-ss-fetch-urls-task.php(271): explode('\n', Array)

#1 /var/www/html/wp-content/plugins/simply-static.3.0.3/src/tasks/class-ss-fetch-urls-task.php(61): Simply_Static\Fetch_Urls_Task->find_excludable(Object(Simply_Static\Page))

#2 /var/www/html/wp-content/plugins/simply-static.3.0.3/src/class-ss-archive-creation-job.php(142): Simply_Static\Fetch_Urls_Task->perform()

#3 /var/www/html/wp-content/plugins/simply-static.3.0.3/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(514): Simply_Static\Archive_Creation_Job->task('fetch_urls')

#4 /var/www/html/wp-content/plugins/simply-static.3.0.3/vendor/a5hleyrich/wp-background-processing/classes/wp-background-process.php(335): WP_Background_Process->handle()

#5 /var/www/html/wp-includes/class-wp-hook.php(308): WP_Background_Process->maybe_handle('')

#6 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)

#7 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)

#8 /var/www/html/wp-admin/admin-ajax.php(188): do_action('wp_ajax_wp_arch...')

#9 {main}
  thrown in /var/www/html/wp-content/plugins/simply-static.3.0.3/src/tasks/class-ss-fetch-urls-task.php on line 271
``

The site runs in a docker container locally, built on Oxygen Page Builder. This error happens even if all plugins except for Simply Static are deactivated.

**Comment by patrickposner** [comment]
Hey @jan-koch,

thanks for your report!

There is a quick fix: go to Simply Static -> Settings->Utilties and click "Migrate Settings".

Once done, you can run your export as usual without any interruptions! 🙂

**Comment by jan-koch** [comment]
Oh nice! I hadn't seen that option, thanks!

Works like a charm now :)
