### ISSUE TITLE
Uncaught TypeError: (0 , e.createRoot) is not a function

### ISSUE THREAD

**Issue by wayandbahramzy** [Simply-Static/simply-static#164]
I am getting this error, just by visiting the page: wp-admin/admin.php?page=simply-static-settings
Uncaught TypeError: (0 , e.createRoot) is not a function

I also tried to install an older version of the plugin 3.0.6, but the same,

wordpress version 6.1.3

this is the browser console log, there are no other errors.
![image](https://github.com/Simply-Static/simply-static/assets/48322176/22069be9-ff25-45b6-a9fe-b009e713b3a5)

but very strange that this plugin is working on other site with wordpress version 6.2.2

does this plugin has any issue with specific versions of wordpress?

**Comment by patrickposner** [comment]
Hey @wayandbahramzy,

thanks for taking the time to create an issue!

Simply Static requires at least WordPress 6.2 since version 3.0.

WordPress 6.2 upgraded the internal React version to 18 (which requires to be initialized with createRoot), while older versions (< React 17) used render() as the method of initialization.

**Comment by wayandbahramzy** [comment]
Thank you for your response, Patrick. I've just updated WordPress to version 6.3, but unfortunately, I'm still encountering issues with generating static files. Strangely, there are no backend errors or browser console log errors being reported.

Upon checking the plugin Diagnostics, I noticed a message indicating that the cURL version is lower than 7.48.

Given this situation, I'd like to inquire about any additional requirements that this plugin might have. Your guidance would be greatly appreciated.

<img width="918" alt="image" src="https://github.com/Simply-Static/simply-static/assets/48322176/48a5e543-7422-4ac2-b149-7909dc7ca7f3">

**Comment by patrickposner** [comment]
Hey @wayandbahramzy,

I would try a couple of things:

1) If that is a project that has Simply Static installed before, go to Simply Static -> Settings -> Utilities and click "Migrate Settings"
2) If you can (and it's not already above that), increase PHP to 8+ (8.0, 8.1, 8.2..)
While it still works with 7.4 - it's much faster with PHP 8.
3) Check that the temporary directory is writeable (in Diagnostics)

**Comment by wayandbahramzy** [comment]
Hey Again, I appreciate your responses, thanks

Unfortunately, the issue still persists. It appears that the problem might be due to the fact that Simply-Static requires at least "curl 7.68.0." As of now, the curl version installed is 7.64.0, which could be the reason for the ongoing problem."

![image](https://github.com/Simply-Static/simply-static/assets/48322176/835ea231-acab-4d29-a7d7-41015db528eb)
