### ISSUE TITLE
Add addional files and directories recursively

### ISSUE THREAD

**Issue by JonnyTech** [Simply-Static/simply-static#165]
The plugin does not export all of my theme files, it is https://themify.me/themes/basic

In Dashboad >> Simply-Static >> Settings >> General >> Include >> Additional Files and Directories:
```
/my-home/wp-content/themes/basic/themify/js/*
/my-home/wp-content/themes/basic/themify/css/*
```
But the files/folders are not exported. If I copy them manually then it is ok.

Is there another syntax that I should use rather than the asterisk wildcard?

**Comment by patrickposner** [comment]
Hey @JonnyTech,

thanks for creating an issue!

Just remove the wildcard at the end of your path.
The wildcard should only be used if you want to use it as a placeholder within a path.

In your case, you want to include the entire directory, so you can reference the path like so:

`/my-home/wp-content/themes/basic/themify/js/`
`/my-home/wp-content/themes/basic/themify/css/`

**Comment by JonnyTech** [comment]
Perfect, that works, thank you so very much.
