### ISSUE TITLE
Does not work with TranslatePress

### ISSUE THREAD

**Issue by alexanderwink** [Simply-Static/simply-static#166]
If using TranslatePress with the setting "Use a subdirectory for the default language" set to "yes" Simply Static will not work as intended. This is probably since this setting will do a redirect to e.g. /en/ for the default language and any files under the root ( / ) will not be included in the zip. All the CSS and JS are located under the root and not within the language folders.

Setting it to "no" will make Simply Static work but then the default language will not have it's own subdirectory.

Let me know if you need any more info on this, maybe I could even help with a PR.

**Comment by patrickposner** [comment]
Hey @alexanderwink,

we are happy to check that, but I will move that issue to the pro version (as we only support multilingual setups within Simply Static Pro).

The last time we checked, it worked fine with that setup, but we don't actively monitor other translation plugins (as WPML is still about 95% across our user base).

Feel free to reach out here for further discussion: https://simplystatic.com/support/
