### ISSUE TITLE
destination_scheme variable is not saved correctly

### ISSUE THREAD

**Issue by nulldrei** [Simply-Static/simply-static#167]
apparently the schema is not saved correctly during the setup of a fresh installation. 

When using absolute urls and selecting https:// as scheme its not saved. the host is displayed in the activity log as follows:
` "[2023-08-30 08:40:03] Destination URL: httpwww.XXXX.com/"`

I exported the settings as a json via the utilities and the destination_scheme only appears there as "http". 
`{ ... "destination_scheme": "http" ... }`

workaround: current workaround for me was to export the json, change the value destination_scheme to "https://" and then import it.

**Comment by patrickposner** [comment]
That does seem to be related to a missing migration: https://wordpress.org/support/topic/bug-replacing-urls/
