### ISSUE TITLE
Generate _redirects file for Cloudflare pages

### ISSUE THREAD

**Issue by theoriginalgri** [Simply-Static/simply-static#198]
Cloudflare pages allows to configure redirects using a `_redirects` file (https://developers.cloudflare.com/pages/configuration/redirects/).

Though Cloudflare pages is not yet a supported deployment method, it would be great to have the option to generate such a file in addition or exclusive to the JavaScript based redirection.

**Comment by patrickposner** [comment]
We do have a similar issue (creating these files for various providers) in the Simply Static Pro repository (as Cloudflare Pages is supported through the GitHub integration already).

That's why I'm closing the issue here.

**Comment by theoriginalgri** [comment]
Thanks! I was actually looking into Simply Static Pro before buying and not aware that this file should then be generated 👍

**Comment by patrickposner** [comment]
We will even try to auto-convert those redirects in the future (WP redirect set up with .htaccess or the Redirects plugin into _redirects file for Cloudflare Pages, GitHub Pages, BunnyCDN, and so on..), but please don't ask for a release date! 😅
