### ISSUE TITLE
Generate different content for mobile and desktop (based on the wp_is_mobile return value)

### ISSUE THREAD

**Issue by mraszplewicz** [Simply-Static/simply-static#199]
I am trying to use Simply Static (btw. it is great!) for a website created with Avada builder.

I have one problem with the "Off Canvas Builder" - one of the conditions for closing a panel is based on the is_mobile attribute which is probably based on the wp_is_mobile function that is based on the User-Agent HTTP header. Website generated with Simply Static returns is_mobile=false regardless of the value of the User-Agent HTTP header.

I wonder if it would be possible to pass the User-Agent HTTP header during the website generation, so it would generate different results for different header values? If yes, then I would host two different versions and serve different static websites for mobile and desktop devices.

Maybe it sounds like an edge-case but I think more plugins rely on the wp_is_mobile function (or User-Agent HTTP header) and serve different content depending on its return value.

**Comment by patrickposner** [comment]
Hey @mraszplewicz,

you can do that already with a filter:

`add_filter('ss_remote_get_args', function( $args ) {
    $args['user-agent'] = 'my custom user agent';
    return $args;
});`

The filter is basically a wrapper around the wp_remote_get() arguments: https://developer.wordpress.org/reference/functions/wp_remote_get/

**Comment by mraszplewicz** [comment]
Thanks @patrickposner I will try it out!
