### ISSUE TITLE
Make generation of static site go faster, Curl website in parallel ?

### ISSUE THREAD

**Issue by thapakazi** [Simply-Static/simply-static#200]
Is there plans to make the crawler go faster, like crawl the site in parallel ??

Crawling the entire site to publish the static build is 🐌 when you have hundred thousands of assets.

**Comment by patrickposner** [comment]
Hey @thapakazi,

thanks for creating an issue.

I would love that, but honestly, that won't happen anytime soon.

Here are a couple of reasons for that:

**Compatibility**

- Parallel requests aren't really working reliably within WordPress.
- Most external APIs limit the number of requests per second (GitHub and BunnyCDN, for example) to avoid abuse, which means we could only implement it for some deployment options (which doesn't make sense to us)
- We increase the risk of timeouts when running an export

**Performance compared to other solutions**

Compared to other solutions (even the cloud ones), we are one of the fastest.

We strive to be the best, but you can do only so much without requiring some SaaS components (like an external crawling engine, for example).

**Wrong approach in general**

Having hundreds of thousands of assets is more likely a misunderstanding of the concept in general.
Simply Static converts WP sites into static ones; it's not an offloading tool for assets (there are way better tools for that).

**A solid setup would be something like:**

WP Offload Media to offload all the assets (media/JS/CSS files) to a CDN.
It will also rewrite the URLs within WordPress to the new CDN URL.

Simply Static will skip fetching and downloading these files and only handles pages.
Some of our users follow this approach with big websites (>250k pages).
