### ISSUE TITLE
GitHub integration delete repo privilege?

### ISSUE THREAD

**Issue by ilkkarinne** [Simply-Static/simply-static#207]
Hi, 
The [Set up the GitHub integration](https://simplystatic.com/docs/setting-up-the-github-integration/#GitHub-Repository) documentation has the following statement:

> Simply Static needs the privileges to read and write repositories, delete repositories, and the user settings (to verify actions).

I'm sure there is a perfectly good reason for requiring the **delete repositories**, but it just seems a bit radical, since the same doc also states that

> We will not create the repository for you; we only have the privileges to push files to it (as configured earlier while creating the personal access token).

I would suggest adding a clarification for why Simply Static needs the delete repo privilege in the mentioned documentation page.

**Comment by patrickposner** [comment]
Hey @ilkkarinne,

thanks for bringing that up!

We should definitely improve that part of the documentation!

To give you a bit more context:

**Deleting Repositories:**

It isn't required to have the privilege of deleting repositories when using the default configuration of Simply Static.
It's only needed if you use the filter _ssp_clear_repository_.

**Creating Repositories:**

We can create repositories automatically on the first API connection. Still, given the different account privileges (especially with organization accounts), we noticed that we do get quite a few edge cases where setting up the repository yourself solves 99% of the problems (especially as it triggers the creation of a base tree for you).

However, if you create the repository yourself and you are not using the filter mentioned above, we will not need the privilege to create a repository.

I think in the long term, we will switch to an oAuth authentication to create the tokens automatically based on a little questionnaire to make it easier (and more understandable) to determine which privileges are required for specific scenarios.
