### ISSUE TITLE
Bug: Class "simply_static_pro\commands\Single" not found

### ISSUE THREAD

**Issue by abugood2015** [Simply-Static/simply-static#212]
Simply Static version: 3.1.6.1
Simply Static Pro version: 1.4.6

Dear @patrickposner 
Your plugin is amazing!
The only problem is, when I run wp-cli to export single post, such as:

> sudo -u www /usr/local/bin/wp --path=/www/wwwroot/xxx.com simply-static run --single=11

Error output:

> Starting to export Blog ID: 1. URL:https://xxx.com
> Preparing for Single Export
> PHP Warning:  include(class-ssp-single.php): Failed to open stream: Permission denied in /www/wwwroot/xxx.com/wp-content/plugins/simply-static-pro-1.4.6/src/wp-cli/class-ssp-commands.php on line 52
> Warning: include(class-ssp-single.php): Failed to open stream: Permission denied in /www/wwwroot/xxx.com/wp-content/plugins/simply-static-pro-1.4.6/src/wp-cli/class-ssp-commands.php on line 52
> PHP Warning:  include(): Failed opening 'class-ssp-single.php' for inclusion (include_path='.:') in /www/wwwroot/xxx.com/wp-content/plugins/simply-static-pro-1.4.6/src/wp-cli/class-ssp-commands.php on line 52
> Warning: include(): Failed opening 'class-ssp-single.php' for inclusion (include_path='.:') in /www/wwwroot/xxx.com/wp-content/plugins/simply-static-pro-1.4.6/src/wp-cli/class-ssp-commands.php on line 52
> PHP Fatal error:  Uncaught Error: Class "simply_static_pro\commands\Single" not found in /www/wwwroot/xxx.com/wp-content/plugins/simply-static-pro-1.4.6/src/wp-cli/class-ssp-run-command.php:164
> Stack trace:
> ...

In file: simply-static-pro-1.4.6/src/wp-cli/class-ssp-run-command.php
need to add this line:

`use simply_static_pro\Single;`

**Comment by abugood2015** [comment]
How to export single post in wp-cli?
@patrickposner

**Comment by abugood2015** [comment]
Should

`Single::get_instance()->prepare_single_export( absint( $options['single'] ) );`

changed to:

`Single::get_instance()->export_single( absint( $options['single'] ) );`

?

**Comment by patrickposner** [comment]
Hey @abugood2015,

it looks indeed like the namespace is missing.

Can you reach out via pro support right here (just include the link to the issue): https://simplystatic.com/support/
This way, I can share an updated beta version with you, and we can explore your pro-related questions a bit more.
