### ISSUE TITLE
can 'ssp_single_auto_export' be used together with 'Clear Directory' option?

### ISSUE THREAD

**Issue by emidiao** [Simply-Static/simply-static#216]
hi, I have set the option 'Clear Director before export' so that when I regenerate the entire site, the previous generation files are deleted from the deployment folder.
However, if I enable the hook 'ssp_single_auto_export', all the files are deleted even when I want to generate only the new published page.
Is there a way to avoid it?

**Comment by patrickposner** [comment]
Fixed now! 🙂
