### ISSUE TITLE
Jetpack Slideshow Displays All Images

### ISSUE THREAD

**Issue by cmccachern** [Simply-Static/simply-static#220]
A Jetpack slideshow shows a single image at a time along with navigation arrows to display additional images in the sideshow gallery.  However, when I export the website with Simply Static, the slideshow shows all images at the same time, and the slideshow functionality is broken. It appears that a couple of files are trying to be loaded, but do not exist in the static site. The console shows a failure to load the following files:

/wp-content/plugins/jetpack/_inc/blocks/958.js
/wp-content/plugins/jetpack/_inc/blocks/swiper.css

To recreate this issue, I create a new website in Local WP, install Jetpack and SimplyStatic, create new post, insert a slideshow with multiple images, and generate the website with SimplyStatic.

I am using the following versions:
Simply Static Version: 3.1.6.3
Jetpack Version 13.3
Local WP Version 8.3.2+6660

This is the expected behavior:
![slideshow-working](https://github.com/Simply-Static/simply-static/assets/6666240/22bf58f6-3b40-4ecd-9c60-a618d72e05c3)

This is what the static version looks like:
![slideshow-broken](https://github.com/Simply-Static/simply-static/assets/6666240/017d76c3-8f1d-414d-b48c-cace2bfa8ff2)

**Comment by tatyana12** [comment]
Yes,  the slideshow shows all images at the same time, and the slideshow functionality is broken.
In Jetpack galleries, I could see html pages but option to click on images is disable.
This is related to Jetpack galleries in about five static Wordpress sides and only one  static Wordpress side allow to  click on images .
This happened when Ising static pages create by Simply Static plugin.
How to make images clickable on all Wordpress side when they converted to static pages using  Simply Static plugin?
Thanks.

**Comment by cmccachern** [comment]
Until this is fixed, I am using the following steps as a workaround:

Simply Static leaves two files out two files required for Jetpack slideshows to work:
- public/wp-content/plugins/jetpack/_inc/blocks/958.js
- public/wp-content/plugins/jetpack/_inc/blocks/swiper.css

Copy these files from the wordpress installation into the static site.

Additionally, absolute urls with the local address end up in the html.  Use this command to
find and replace those instances (replace "my-website" with your Local website name):

find public -type f \( -name \*.html \) -exec sed -i "" "s/https:\/\/my-website.local\//\//g" {} \;

Note that the local address is also found in xml, css, and js. However, replacing it in the html seems to
fix the slideshow breaking issue.

**Comment by tatyana12** [comment]
Actually one of my WordPress side is working fine with Jetpack galleries but others are not. The pattern of address of working side is different compare with pattern s of the not working sides since the working side is automatically created in the root file system but others are on the subdirectories.
I think need to figure out why this particular websaite is working properly and  change the paths of not working websites accordingly.
thanks.

**Comment by tatyana12** [comment]
One of my website is working after converting  to static  using Simply Static 
 but others sides are not.
If I get secret link, I could share paths with a  static version of the working and not working websites for comparision.
Thanks.

**Comment by tatyana12** [comment]
Hello,You wrote:
Use this command to
find and replace those instances (replace "my-website" with your Local website name):

find public -type f ( -name *.html ) -exec sed -i "" "s/https://my-website.local////g" {} ;
Where to type this command that it takes effect?thanks.
    On Sunday, May 12, 2024, 09:06:49 PM PDT, cmccachern ***@***.***> wrote:  
 
 


Until this is fixed, I am using the following steps as a workaround:

Simply Static leaves two files out two files required for Jetpack slideshows to work:
   
   - public/wp-content/plugins/jetpack/_inc/blocks/958.js
   - public/wp-content/plugins/jetpack/_inc/blocks/swiper.css

Copy these files from the wordpress installation into the static site.

Additionally, absolute urls with the local address end up in the html. Use this command to
find and replace those instances (replace "my-website" with your Local website name):

find public -type f ( -name *.html ) -exec sed -i "" "s/https://my-website.local////g" {} ;

Note that the local address is also found in xml, css, and js. However, replacing it in the html seems to
fix the slideshow breaking issue.

**Comment by tatyana12** [comment]
For some reason one of my static website woks properly without but others don't .  The http address are different on those website. Working website has absolute http address .  I could send the address if you provide me with the secret link since those websites are private.  thanks.

**Comment by patrickposner** [comment]
Hey @cmccachern and @tatyana12,

thanks for all the details!

The following configuration seems to fix the issue reliably:

![jetpack-issue](https://github.com/Simply-Static/simply-static/assets/15874198/d464a7e7-503b-40e5-841d-05af8cc52644)

I'm not sure if it's big enough of a problem for a custom integration; we might just add it as part of the documentation for now.

**Comment by tatyana12** [comment]
Hello,
It is not fixed when I've changed setting as you directed  by using  absolute  path instead of the relative path. The images in Jetpack galleries don't clickable and slideshows are not available. Also  my website that was working before with absolute path doesn't work anymore with slideshow.  How to make Jetpack galleries work with Simply Static plugin?  Thanks

**Comment by tatyana12** [comment]
Some addition. I've updated Simply Static plugin(using offline option) but still there are no slideshow in the static of all websites except one. Thanks.

**Comment by tatyana12** [comment]
Demos provided by teach support of this plugin show that even paid version of this plugin doesn't work with Jetpack galleries providing slide shows and clickable images.

**Comment by patrickposner** [comment]
@cmccachern @tatyana12 

We will automatically include these files with the next update.

**Comment by tatyana12** [comment]
Would you please indicate when next update that supposed to fix issues with clickable  images and slideshows  in Jetpack galleries  will take place?
THanks.
