### ISSUE TITLE
Simply Static drastically slows down the admin panel

### ISSUE THREAD

**Issue by matt08** [Simply-Static/simply-static#236]
In the new version, the plugin drastically slows down the performance of the WordPress admin panel on the pages.

With each refresh and any operation in the admin panel, the plugin calls all URLs that are added in Simple Static as INCLUDE -> ADDITIONAL URLS.

Screen from Query Monitor:
![CleanShot 2024-07-16 at 19 30 38@2x](https://github.com/user-attachments/assets/861ea02a-ffe7-48d0-98af-500504e47299)

Solution: disable checking all additional URLs in the panel in views other than the plugin's own view.

**Comment by patrickposner** [comment]
Fixed now and will be included in today's update:

![Screenshot 2024-07-17 at 08 39 48](https://github.com/user-attachments/assets/028080b3-5fcb-4c2c-a265-41aca6fde763)
