### ISSUE TITLE
Editor screen freezes when loading patterns with file blocks

### ISSUE THREAD

**Issue by rdoughbs** [Simply-Static/simply-static#250]
Ran into a weird issue. If Simply Static plugin is enabled and you have a pattern that contains a file block w/ download button toggled off, then Wordpress editor screen will freeze 90% of the time.

Steps to replicate:
1. Enable Simply Static
2. Create a new pattern with a File block. Toggle off "Show download button" button. 
3. Edit a post and add the pattern you created.

The editor seems to load fine if you have "Show download button" toggled on. 

My work around for now is to prevent Simply Static from loading on certain requests.

```
# simply-static.php
# don't load plugin if editing
if ( !( (isset( $_GET['context'] ) && $_GET['context'] === 'edit') || (isset( $_GET['action'] ) && $_GET['action'] === 'edit') ) ){
   add_action( 'plugins_loaded', 'simply_static_run_plugin' );
}
```

```
# class-ss-plugin.php
# don't run Upgrade_Handler on wp-json requests
if ( strpos($_SERVER['REQUEST_URI'], 'wp-json') === false) {
  // Maybe run upgrade.
  Upgrade_Handler::run();
}
```

**Comment by rdoughbs** [comment]
Forgot to mention that this just started on Wordpress 6.6

**Comment by patrickposner** [comment]
@rdoughbs thanks for the report, looking into it!

**Comment by rdoughbs** [comment]
@patrickposner, I'm having the same issues when Simply Static is disabled, so I think it is something in Wordpress core. I added a comment to this issue in Gutenberg because it seems related: https://github.com/WordPress/gutenberg/issues/64514
