### ISSUE TITLE
exported HTML of <script> tags of type "text/html" or "text/template" are all missing closing </script> tag, since 3.1.7

### ISSUE THREAD

**Issue by omegabenefits** [Simply-Static/simply-static#255]
I've just downloaded every version of simply-static (free) I could get my hands on to figure out where this broke - and I had to go all the way back to the 3.1.7 release to get HTML exports that weren't missing the closing </script>! (tried 3.1.8, 3.1.7.4, 3.1.7.2)

When an inline script using templates (underscore.js) like the block below is parsed by simply-static
```
<script type="text/html" id="tmpl-autocomplete-header">
	<div class="autocomplete-header">
		<div class="autocomplete-header-title">{{{ data.label }}}</div>
		<div class="clear"></div>
	</div>
</script>
```
the resulting exported HTML is missing the closing </script> tag, breaking that script completely (but frustratingly NOT throwing any errors to the console, making the bug hard to track down!). A series of similar inline scripts then all get busted, as the first script is never closed and the rest are all treated as if they're nested (but none ever close)
```
<script type="text/html" id="tmpl-autocomplete-header">
	<div class="autocomplete-header">
		<div class="autocomplete-header-title">{{{ data.label }}}</div>
		<div class="clear"></div>
	</div>

```
This bug has been responsible for silently breaking our implementation of WP Search with Algolia plugin (I know SS complains it's not compatible, but we don't use the SS algolia integration, have been using the separate plugin for a long time with SS already). But I would imagine it's affecting any other templating scripts too.

Also found some Elementor inline scripts as well that use type="text/template" also have missing </script> tags since 3.1.7, breaking some functionality I didn't even notice.

**Comment by omegabenefits** [comment]
since the only mention of parsing "text/html" scripts I could find in the source belonged to vendor/voku/simple_html_dom, and there appears to be a bump in composer.json from 4.8.8 to 4.8.9 (commit 5ba7de2) right around the time when simply-static didn't have this issue, curious if simple_html_dom is involved in the bug?

**Comment by patrickposner** [comment]
@omegabenefits thanks for the report!

Can you temporarily add the following code snippet, re-run the export, and check if the issue persists?

```php
add_filter('ss_parse_inline_script', '__return_false' );
``` 

That should help getting a better idea if it's related to our changes or something associated with the underlying composer package.

**Comment by omegabenefits** [comment]
adding that filter did not fix the issue, still missing </script>

**Comment by patrickposner** [comment]
Hey @omegabenefits,

thanks for the update!

Do you know how the script gets injected into the page?
I just tried to replicate it by adding it to the footer of the page with:

`add_action( 'wp_footer', function () {
	?>
    <script type="text/html" id="tmpl-autocomplete-header">
        <div class="autocomplete-header">
            <div class="autocomplete-header-title">{{{ data.label }}}</div>
            <div class="clear"></div>
        </div>
    </script>
	<?php
} );`

When I then run the static export (ZIP/offline), the result looks fine (the closing tag is there, no invalid HTML):

![Screenshot 2024-09-13 at 11 50 59](https://github.com/user-attachments/assets/be4c3e0e-ddc3-46e2-bf03-8c32dd785c7f)
