### ISSUE TITLE
everytime call `create_or_update_table()`

### ISSUE THREAD

**Issue by imjlk** [Simply-Static/simply-static#256]
After installing the latest version of the plugin, I noticed that the page speed was slower than before.

Inspect with query monitor plugin, i found that `create_or_update_table` function is calling everytime.

The changes in this [commit](https://github.com/Simply-Static/simply-static/commit/e18e24efe7586f3cea01cf82341a03d5c34c7c74#diff-170d8c764219d89eea21e3c0fb0583f446c4f3dbffaaae0aa28c2e2daefad369L185-R195) make sense, but the problem occurs when it checks for the [first time](https://github.com/Simply-Static/simply-static/blob/a773d99b59e8e1f9f25f96838f47be7d0aa4a1b5/src/class-ss-upgrade-handler.php#L181-L187):
```php
		$version = self::$options->get( 'version' );


		// New installation, set default options.
		if ( null === $version ) {
			Page::create_or_update_table();
			self::set_default_options();
		} else {
```

The default options are set, but the version is missing in the [options array](https://github.com/Simply-Static/simply-static/blob/a773d99b59e8e1f9f25f96838f47be7d0aa4a1b5/src/class-ss-upgrade-handler.php#L71).
So it keeps getting called because the version is not stored in the wp_options table.

I hope this information helps in resolving the issue. Thank you for your attention, and I look forward to any updates

**Comment by patrickposner** [comment]
@imjlk excellent catch!

I'll get that included in the next update!
