### ISSUE TITLE
Some pages missing in exports, even with Sitemap linked on homepage

### ISSUE THREAD

**Issue by Zacatero** [Simply-Static/simply-static#268]
I noticed that I have to run the export four or five times before I get every page exported. Even with a sitemap that links to everything present in the footer on the homepage, I find I have to export it that many times before I get a full collection of everything. And sometimes, it only pulls the homepage and nothing else.

Is there anything I can do to make this more consistent? Is there a way for me to tell the SimplyStatic tool what my Sitemap is so it ALWAYS looks at that sitemap and all of the links within it, etc?

**Comment by Zacatero** [comment]
Just to add to this, it feels odd that it relies entirely on the crawler when Wordpress has a whole function for "Pages" and "Posts", why not just go based off of those lists at least, and then use the crawler for everything else?

**Comment by Zacatero** [comment]
@EllyKher I switched to Apache, and now it just stays on "Fetched 0 of 1 pages/files" forever. I have noticed an improvement in other ways, like if I hit cancel it actually cancels instead of just timing out later, but I can't get it to actually work now on Apache. Do I need to also do something else?

**Comment by twintersx** [comment]
@Zacatero did you ever figure this out?

**Comment by Zacatero** [comment]
I did @twintersx!

For some reason the first time I switched it to Apache, the static export never worked. But then later I tried switching it again and now it works perfectly on Apache!
