### ISSUE TITLE
Basic Authentication

### ISSUE THREAD

**Issue by jkirrane** [Simply-Static/simply-static#273]
### Current Behavior:
When Basic Authentication is enabled, the Simply Static `Plugin::add_http_filters()` method overwrites all Authorization headers, even if they are to other remote services like Github.

### Expected Behavior:
The Simply Static `Plugin::add_http_filters()` method should only set the Authorization header when making requests to pages to generate static content, not when requesting other websites.

### Steps To Reproduce:
1. Install current versions of the Simply Static and Simply Static Pro plugins.
2. Enable and configure Basic Authentication 
3. Enable Github deployment and store a Github Personal Token
4. The `http_request_args` filter in Simply Static will overwrite the Github Authorization header with the Basic Authentication value generated in the Simply Static `Plugin::add_http_filters()` method

It looks like this is caused by this change to Simply Static https://github.com/Simply-Static/simply-static/commit/5d30cc7f64698389070f5e94567fac9751ea4a01 where the filter no longer checks to see if the target URL is part of the website domain.

I am uncertain if the change to the Simply Static plugin should be reverted or maintained, but if it is maintained then this plugin will need to be updated to remove that filter in certain conditions. In my preliminary testing removing the filter in `/simply-static-pro/src/deployment/github/class-ssp-github-blobs-task.php` at the start of the `perform()` method should work, since there are no longer any calls to the website server that I am aware of.

I have not tested this with other deployment options.

Also note that I have created this issue in this repository and the Simply Static Pro one, since I'm not sure how you will want to resolve this.

**Comment by patrickposner** [comment]
Great catch @jkirrane!

I merged the PR now and did a test based on your instructions, and it seems to be solved now:

![Screenshot 2024-11-13 at 11 00 42](https://github.com/user-attachments/assets/9fb26226-7575-449a-9184-7110cf709d03)

I already included it in the next release and will do an update on w.org in a minute!
