### ISSUE TITLE
The `Use relative URLs` option should not affect RSS feeds

### ISSUE THREAD

**Issue by davidbgk** [Simply-Static/simply-static#51]
As of the feed specification, an RSS feed should only contain absolute links. Otherwise, (remote) aggregators will not be able to link to the entry.

If I read correctly what happens [around here](https://github.com/patrickposner/simply-static/blob/master/src/class-ss-url-extractor.php#L410) this is not taken into consideration.

I'm only guessing while debugging the feed of a friend, I don't know PHP and I don't use Wordpress so I'm just trying to figure out the issue while looking at public screenshots 😅

**Comment by patrickposner** [comment]
Hey @davidbgk,

I agree RSS feeds should stay as absolute URLs, but so should schema URLs, XML-Sitemap URLs, and a bunch of other cases.

This is something Simply Static should cover. 
The major question is how we handle that.

If you select "Relative Path", you don't provide an absolute URL that Simply Static can use for the search & replace method.

Not replacing the URL and using the old WP URL would also be wrong - so we may need an additional option if  "Relative Path" is selected to cover that.

**Comment by davidbgk** [comment]
Hey @patrickposner,

I agree that a new dedicated setting would be more pertinent in that case 👍

**Comment by nadirvishun** [comment]
Is additional option for `rss` or `sitemap` currently supported? No relevant configurations found anywhere.
