### ISSUE TITLE
Moving to Action Scheduler

### ISSUE THREAD

**Issue by patrickposner** [Simply-Static/simply-static#60]
We are currently using [WP Background Processing](https://github.com/deliciousbrains/wp-background-processing) for managing and queuing tasks.

While this works fine right now, it seems that there isn't much maintenance going on here.
There are also a couple of issues that do affect Simply Static:

- [https://github.com/deliciousbrains/wp-background-processing/issues/88](https://github.com/deliciousbrains/wp-background-processing/issues/88)
- [https://github.com/deliciousbrains/wp-background-processing/issues/61](https://github.com/deliciousbrains/wp-background-processing/issues/61)
- [https://github.com/deliciousbrains/wp-background-processing/issues/39](https://github.com/deliciousbrains/wp-background-processing/issues/39)

We should move to [Action Scheduler](https://actionscheduler.org/) to have a better maintained library + an admin UI for cancelling/restarting jobs from the backend and to use WP-CLI to handle jobs more efficiently.

**Comment by stellarpower** [comment]
`wp-cli` suport sounds good to me - is there currently a way to trigger generating the export programmatically? Be this a web request or through a CLI command on the installation machine. I see a further plugin that can execute a callback once finished, which is nice.

Thanks!

**Comment by patrickposner** [comment]
Hey @stellarpower,

there is a deep integration now with WP-CLI, but it's part of Simply Static Pro.
With that, you can control everything (modify settings, directories) and run all kinds of exports (single, full export, builds).

However, you can also use a code snippet to start the process programmatically.
Here is a little example I built a while ago: https://simplystatic.com/docs/code-snippets/

**Comment by stellarpower** [comment]
Brilliant, thanks a lot!

**Comment by patrickposner** [comment]
We skip that and explore other options not so close to WooCommerce.

We might even offer an option to use an external queue system in the future.
